// Generated by CoffeeScript 1.3.3
var myAlert;

myAlert = function(before, message) {
  return $(before).after($("<div>").attr("class", "alert alert-error fade in").text(message).append($("<button>").attr("class", "close").attr("data-dismiss", "alert").html("&times;")));
};

$(function() {
  $("#get_name").click(function() {
    return $("#subject01_result").text($("#yamada_name").html());
  });
  $("#add_sakurako").click(function() {
    if ($("#member_list > #sakurako").size() > 0) {
      return myAlert($("#member_list"), "櫻子さんは追加済みです。");
    } else {
      return $("#member_list").append($("<li>").attr("id", "sakurako").text("櫻子"));
    }
  });
  $("#add_himawari").click(function() {
    if ($("#member_list > #himawari").size() > 0) {
      return myAlert($("#member_list"), "向日葵さんは追加済みです。");
    } else {
      return $("#member_list").append($("<li>").attr("id", "himawari").text("向日葵"));
    }
  });
  $("#remove_akari").click(function() {
    if ($("#member_list_remove > #akari").size() === 0) {
      return myAlert($("#member_list_remove"), "あかりさんは削除済みです。");
    } else {
      return $("#member_list_remove > #akari").remove();
    }
  });
  $("#change_visible_momo").click(function() {
    return $("#stealth_momo").toggle();
  });
  return $("#change_header_html").click(function() {
    return $("h2").each(function() {
      return $(this).text("【" + ($(this).text()) + "】");
    });
  });
});
